# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 25.00
  max_exploration_time: 1000

supereight:
  general:
    sequence_name:              "gazebo_powerplant"
  map:
    size:                       512
    dim:                        51.2
    aabb_min_W:                 [-16.5, -15.5,  0.0]
    aabb_max_W:                 [ 16.5,  15.5, 26.0]
    sampling_min_W:             [-16.5, -15.5,  0.7]
    sampling_max_W:             [ 16.5,  15.5, 25.0]
    frontier_cluster_min_ratio: 0.015625
  sensor:
    near_plane:                 0.02
    far_plane:                  7.0
  exploration:
    delta_t:                    0.20
    linear_velocity:            2.5
