# SPDX-FileCopyrightText: 2020-2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 600
  dataset: "Matterport3D"

# Habitat-ROS node settings
habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/1LXtFkjw3qL/1LXtFkjw3qL.glb"
  initial_T_HB: [0.0, 0.0, 0.0]

# Supereight settings
supereight:
  general:
    sequence_name:              "matterport3d_1LXtFkjw3qL"

  map:
    size:                       1024
    dim:                        40.96

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

