# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 1800 # 30 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/29hnd4uzFmX/29hnd4uzFmX.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_29hnd4uzFmX"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.6330390048678964, 0.34894117806106806, 0.345402104256209]
