# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/D7N2EKCX4Sj/D7N2EKCX4Sj.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_D7N2EKCX4Sj"
  map:
    size:                       1024
    dim:                        40.96
    t_MW_factor:                [0.4693560996092856, 0.5968913431279361, 0.44855408440344036]
