# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/e9zR4mvMWw7/e9zR4mvMWw7.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_e9zR4mvMWw7"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [-0.09660799452103673, 0.4998933169990778, 0.4390644486993551]
