# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/EU6Fwq7SyZv/EU6Fwq7SyZv.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_EU6Fwq7SyZv"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.27485439158044755, 0.7295525278896093, 0.34009103500284255]
