# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/gZ6f7yhEvPG/gZ6f7yhEvPG.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_gZ6f7yhEvPG"
  map:
    size:                       256
    dim:                        10.24
    t_MW_factor:                [0.5383571488782763, 0.49258246971294284, 0.2448449832006645]
