# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/JeFG25nYj2p/JeFG25nYj2p.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_JeFG25nYj2p"
  map:
    size:                       1024
    dim:                        40.96
    t_MW_factor:                [0.4910671846009791, 0.5425466278102249, 0.46653329872060567]
