# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/jh4fc5c5qoQ/jh4fc5c5qoQ.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_jh4fc5c5qoQ"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.1975006884895265, 0.41476702271029353, 0.3839940279140137]
