# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/oLBMNvg9in8/oLBMNvg9in8.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_oLBMNvg9in8"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.48638685792684555, 0.5344612984918058, 0.35447029466740787]
