# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/pa4otMbVnkk/pa4otMbVnkk.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_pa4otMbVnkk"
  map:
    size:                       1024
    dim:                        40.96
    t_MW_factor:                [0.42520775413140655, 0.1432875188475009, 0.41472240653820336]
