# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/Pm6F8kyY3z2/Pm6F8kyY3z2.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_Pm6F8kyY3z2"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.5035429955460131, 0.3399524250999093, 0.42026778345461935]
