# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/PuKPg4mmafe/PuKPg4mmafe.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_PuKPg4mmafe"
  map:
    size:                       2048
    dim:                        81.92
    t_MW_factor:                [0.5643980223685503, 0.7838814281858505, 0.48584271816071123]
