# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/q9vSo1VnCiC/q9vSo1VnCiC.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_q9vSo1VnCiC"
  map:
    size:                       1024
    dim:                        40.96
    t_MW_factor:                [0.5067307846620679, 0.5287942937575281, 0.4616569624777185]
