# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/S9hNv5qa7GM/S9hNv5qa7GM.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_S9hNv5qa7GM"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.8042880271095784, 0.5057084136642516, 0.3606197477784008]
