# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/TbHJrupSAjP/TbHJrupSAjP.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_TbHJrupSAjP"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.40138636203482747, 0.21283877093810588, 0.4097068386618048]
