# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/ur6pFq6Qu1A/ur6pFq6Qu1A.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_ur6pFq6Qu1A"
  map:
    size:                       2048
    dim:                        81.92
    t_MW_factor:                [0.5893954653292894, 0.26931321871234104, 0.48059556673979387]
