# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/VFuaQ6m2Qom/VFuaQ6m2Qom.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_VFuaQ6m2Qom"
  map:
    size:                       1024
    dim:                        40.96
    t_MW_factor:                [0.6954107778146863, 0.2348285629414022, 0.4531518202275038]
