# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700 # 45 minutes
  dataset: "Matterport3D"

habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/x8F5xyUWy9e/x8F5xyUWy9e.glb"
  initial_T_HB: [0.0, 0.0, 1.4]

supereight:
  general:
    sequence_name:              "matterport3d_x8F5xyUWy9e"
  map:
    size:                       512
    dim:                        20.48
    t_MW_factor:                [0.6145940041169524, 0.5066394917666912, 0.3825822982325917]
