# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

supereight_ros:
  control_interface: "habitat"
  visualize_360_raycasting: true

supereight:
  general:
    sequence_name:              "experiment_handheld"

  sensor:
    # Intel RealSense D455, serial number 032522250421
    intrinsics: [383.432, 383.089, 314.521, 254.927]
    # Using the d455_ros vicon object which is x-forward, z-up
    T_BC:       [ 0.03916, -0.03994,  0.99843,  0.03087,
                 -0.99920, -0.00909,  0.03883,  0.03956,
                  0.00752, -0.99916, -0.04026,  0.00735,
                  0.00000,  0.00000,  0.00000,  1.00000]

