# SPDX-FileCopyrightText: 2021 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2021 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  enable_tracking: false
  enable_rendering: true
  enable_rgb: true
  enable_objects: true
  input_res: [640, 480]
  pose_topic_type: "geometry_msgs::TransformStamped"
  pose_buffer_size: 100
  depth_buffer_size: 10
  rgb_buffer_size: 10
  max_timestamp_diff: 0.035 # > 1/30, used to ensure depth and RGB at 30 FPS always match
  center_at_first_position: false
  visualization_rate: 0
  visualization_max_z: 4.0
  visualize_360_raycasting: false
  max_exploration_time: .NaN
  run_segmentation: true
  dataset: "Real"
  control_interface: "SRL"

# Supereight settings
supereight:
  general:
    sequence_name:              "experiment"
    sequence_type:              "ros"
    log_path:                   "$ROS_LOG_DIR/latest/logs"
    output_render_path:         "$ROS_LOG_DIR/latest/renders"
    enable_meshing:             true
    output_mesh_path:           "$ROS_LOG_DIR/latest/meshes"
    # Rates
    tracking_rate:              1
    integration_rate:           1
    rendering_rate:             1
    meshing_rate:               20
    fps:                        0.0
    # Other
    drop_frames:                false
    max_frame:                  -1
    icp_threshold:              1e-5
    bilateral_filter:           false
    pyramid:                    [10, 5, 4]

  map:
    size:                       128
    dim:                        10.24
    t_MW_factor:                [0.501, 0.501, 0.501]
    aabb_min_W:                 [-5.0, -5.0, -1.0]
    aabb_max_W:                 [ 5.0,  5.0,  5.0]
    sampling_min_W:             [-1.6, -1.7,  0.3]
    sampling_max_W:             [ 2.0,  1.3,  1.6]

  sensor:
    # Intel RealSense D455, serial number 032522250144
    intrinsics:                 [383.82887452833955, 383.75919963826715, 317.05689912848419, 247.29954984050548]
    distortion:                 [-0.044746140719468391, 0.032108748950621074, -0.00035536306453970006, 0.00029686791295286188]
    downsampling_factor:        2
    # Using the s550_jetson vicon object which is x-forward, z-up
    T_BC:                       [ 0.11853000664418434,  -0.47490073656983617,   0.87202060063415754,  0.12889563920908803,
                                 -0.99292555568142049,  -0.062909475092444378,  0.10070371799658612,  0.00040333041457984856,
                                  0.007034088403793104, -0.8777879518135463,   -0.47899773825281011, -0.053578667787259872,
                                  0, 0, 0, 1]
    init_T_WB:                  [1, 0, 0, 0,
                                 0, 1, 0, 0,
                                 0, 0, 1, 0,
                                 0, 0, 0, 1]
    near_plane:                 0.4
    far_plane:                  4.0

  exploration:
    enable_exploration:        true
    num_candidates:            20
    frontier_sampling_probability: 0.5
    utility_weights:           [0.001, 0.998, 0.001]
    use_pose_history:          true
    raycast_width:             36
    raycast_height:            10
    linear_velocity:           0.4
    angular_velocity:          0.5
    robot_radius:              0.4
    safety_radius:             0.0
    min_control_point_radius:  0.1
    skeleton_sample_precision: 0.05
    solving_time:              0.01
    # The thresholds used for the controller are hardcoded in the
    # initialWaypointMsg in publish_full_state_trajectory()
    goal_xy_threshold:         0.20
    goal_z_threshold:          0.20
    goal_roll_pitch_threshold: 0.26 # ~15 degrees
    goal_yaw_threshold:        0.15 # ~8.5 degrees

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

