# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 2.40
  max_exploration_time: 600

# Supereight settings
supereight:
  map:
    size:                       512
    dim:                        51.2
    aabb_min_W:                 [-10.0, -10.0, 0.0]
    aabb_max_W:                 [ 10.0,  10.0, 2.5]
    sampling_min_W:             [-10.0, -10.0, 1.2]
    sampling_max_W:             [ 10.0,  10.0, 1.8]
    frontier_cluster_min_ratio: 0.015625

  exploration:
    delta_t:                    0.25

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

