# SPDX-FileCopyrightText: 2020-2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 3.5
  max_exploration_time: 2700
  dataset: "Matterport3D"

# Habitat-ROS node settings
habitat:
  scene_file: "~/Documents/Datasets/Matterport3D/v1/tasks/mp3d_habitat/mp3d/2n8kARJN3HM/2n8kARJN3HM.glb"
  initial_T_HB: [0, 2.0, 1.5]

# Supereight settings
supereight:
  general:
    sequence_name:              "matterport3d_2n8kARJN3HM"

  map:
    size:                       2048
    dim:                        81.92

  exploration:
    frontier_sampling_probability: 1.0
    utility_weights:        [1.0, 0.0, 0.0]

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

