# SPDX-FileCopyrightText: 2020-2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2020-2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 3.6
  max_exploration_time: 1800
  dataset: "Replica"

# Habitat-ROS node settings
habitat:
  scene_file: "~/Documents/Datasets/Replica/apartment_0/habitat/mesh_semantic.ply"
  initial_T_HB: [0.0, 0.0, 0.0]

# Supereight settings
supereight:
  general:
    sequence_name:              "replica_apartment_0"

  map:
    size:                       512
    dim:                        20.48

  exploration:
    frontier_sampling_probability: 1.0
    utility_weights:        [1.0, 0.0]

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

