#!/bin/sh
set -eu

# Add the time to the supplied TSV stats by reading it from the fusion stats.
add_time_to_tsv() {
	# https://git.sr.ht/~sotirisp/tsvutils
	# Do nothing if the Time column already exists.
	if grep -q '^Time \(s\)	' "$1"
	then
		return
	fi
	fusion="${1%/*}/stats_fusion.tsv"
	{
		printf 'Time (s)\t'
		head -n 1 "$1"
		tsvcut '^Frame$' < "$1" | tail -n +2 | while IFS= read -r frame
		do
			tsvcut '^Frame$' '^Timestamp$' < "$fusion" |
				tail -n +2 | grep '^'"$frame"'\.000000' |
				tail -n 1 | cut -f 2 | tr -d '\n'
			printf '\t'
			tail -n +2 "$1" | grep '^'"$frame"'	'
		done
	} > "$1".tmp
	mv "$1".tmp "$1"
}



if [ "$#" -eq 0 ]
then
	printf 'Usage: %s TSV...\n' "${0##*/}" >&2
	exit 2
fi

while [ "$#" -gt 0 ]
do
	add_time_to_tsv "$1"
	shift
done
