#!/bin/sh
# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0
set -eu

if [ "$#" -eq 0 ]
then
	printf 'Usage: %s RUNDIR ...\n' "${0##*/}"
	exit 2
fi

while [ "$#" -gt 0 ]
do
	printf 'Compressing meshes in %s\n' "$1"
	find "$1" -type d -name 'meshes_*' | sort -r | tail -n +2 | while IFS= read -r dir
	do
		archive=${dir%%/}.tar.gz
		printf 'tar -czf %s -C %s . && rm -rf %s\n' \
			"$archive" "$dir" "$dir"
	done | parallel
	shift
done
