#!/bin/sh
set -eu

if [ "$#" -lt 2 ]
then
	printf 'Usage: %s PLOTDIR LOGDIR...\n' "${0##*/}"
	exit 2
fi

script_dir=$(dirname "$0")
plot_dir="$1"
mkdir -p "$plot_dir"
shift
"$script_dir"/semanticeight-plot -o "$plot_dir"/volume.png volume "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/volume_frame.png volume_frame "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/frame_time.png frame_time "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/planning_time.png planning_time "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/frame_planning_time.png frame_planning_time "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/object_scale.png object_scale "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/utility.png utility "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/gain.png gain "$@"
"$script_dir"/semanticeight-plot -o "$plot_dir"/dominant_gain.png dominant_gain "$@"

