#!/bin/sh
set -eu

if [ "$#" -lt 2 ]
then
	printf 'Usage: %s PLOTDIR LOGDIR...\n' "${0##*/}"
	exit 2
fi

script_dir=$(dirname "$0")
plot_dir="$1"
mkdir -p "$plot_dir"
shift

plots='bg
bg_acc
bg_dist
dominant_gain
frame_planning_time
frame_time
gain
objects
objects_acc
objects_dist
planning_time
utility
volume
volume_frame'

for p in $plots
do
	printf 'Plotting %s\n' "$p"
	"$script_dir"/semanticeight-plot -o "$plot_dir/$p.png" "$p" "$@"
done
