#!/bin/sh
# SPDX-FileCopyrightText: 2022 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2022 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0
set -eu

usage() {
	printf 'Usage: %s DIR ...\n' "${0##*/}"
}

script_dir() {
	dirname "$0"
}

generate_run_montages() {
	render_dir="$1"/renders
	if [ -d "$render_dir" ]
	then
		printf 'Generating render montage...\n'
		"$(script_dir)"/../semanticeight/se_tools/semanticeight_render_montage.sh "$render_dir" && rm -rf "$render_dir"
	else
		printf 'Skipping render montage, %s is not a directory\n' "$render_dir"
	fi
	planning_dir="$1"/planning
	if [ -d "$planning_dir" ]
	then
		printf 'Generating planning montage...\n'
		"$(script_dir)"/../semanticeight/se_tools/semanticeight_planning_montage.sh "$planning_dir" && rm -f "$planning_dir"/*.png
	else
		printf 'Skipping planning montage, %s is not a directory\n' "$planning_dir"
	fi

}



if [ "$#" -eq 0 ]
then
	usage
	exit 2
fi

i=1
while [ "$#" -gt 0 ]
do
	printf '%d/%d\n' "$i" "$#"
	generate_run_montages "$1"
	i=$((i+=1))
	shift
done
