#!/bin/sh
set -eu

script_dir() {
	dirname "$0"
}

# Usage: store_run_data OUTDIR INDEX
store_run_data() {
	# Resolve the symlink to the latest log directory.
	log_dir=$(readlink -f "$HOME/.ros/log/latest")
	# Store the log directory in OUTDIR prefixed with the run index.
	outdir=$(printf '%s/%03d_%s' "$1" "$2" "$(basename "$log_dir")")
	mkdir -p "$1"
	mv "$log_dir" "$outdir"
	printf '%s\n' "$outdir"
}

generate_run_plot() {
	"$(script_dir)"/semanticeight-plot -o "$1"/plots.png "$1"/logs
}

generate_combined_plot() {
	image_file="$1"
	shift
	"$(script_dir)"/semanticeight-plot -o "$image_file" "$@"
}

generate_run_montage() {
	render_dir="$1"/renders
	if [ -d "$render_dir" ]
	then
		"$(script_dir)"/../semanticeight/se_tools/semanticeight_render_montage.sh "$render_dir"
	fi
}



if [ "$#" -lt 2 ]; then
	printf 'Usage: %s NUM LAUNCH_FILE [ARG]...\n' "$(basename "$0")"
	exit 2
fi

dir="$HOME/semanticeight_logs_$(date '+%Y%m%d_%H%M%S')"
n="$1"
shift

# Run the command n times and save the logs.
i=1
while [ "$i" -le "$n" ]; do
	printf 'Run %d/%d\n' "$i" "$n"
	roslaunch supereight_ros "$@"
	run_dir=$(store_run_data "$dir" "$i" "$1")
	generate_run_plot "$run_dir"
	generate_run_montage "$run_dir"
	i=$((i+1))
done

generate_combined_plot "$dir"/plots.png "$dir"/*/logs

