#!/bin/sh
set -eu

usage() {
	printf 'Usage: %s [-o FILE] LOGDIR...\n' "${0##*/}"
}

# Usage: get_column_index FILE COLUMN_NAME
get_column_index() {
	awk '
		BEGIN { FS = "\t" }
		NR == 1 {
			for (i = 1; i <= NF; i++) {
				if ($i == "'"$2"'") {
					print i
				}
			}
		}
	' "$1"
}

# Usage: plot_data LOGDIR...
plot_data() {
	# Set default values for options.
	save_command=${save_command:-''}

	# Iterate over each log directory and find the planning stats.
	planning_files=""
	while [ "$#" -gt 0 ]; do
		f="$1/stats_planning.tsv"
		planning_files="$planning_files	$f"
		# Get the indices of the required columns.
		plan_idx=$(get_column_index "$f" 'Planning iteration')
		dom_idx=$(get_column_index "$f" 'Exploration dominant')
		shift
	done

	# Plot the data.
	gnuplot -p -e "
	$save_command
	planning_files = \"$planning_files\";
	set grid;
	set style data lines;

	set xlabel 'Planning iteration';
	set ylabel 'Dominant gain';
	set yrange [-0.2:1.2];
	set ytics ('Object LoD' 0, 'Exploration' 1);
	plot for [f in planning_files] f using (\$$plan_idx+1):$dom_idx notitle
	"
}



# Parse command line options.
while getopts 'o:h' opt_name; do
	case "$opt_name" in
		o) # FILE   Save to FILE instead of displaying
			save_command="set terminal png size 1920,1080; set output '$OPTARG';"
			;;
		h) #        Display this help message
			usage
			exit 0
			;;
		*)
			usage
			exit 1
			;;
	esac
done
shift "$((OPTIND - 1))"

case "$#" in
	0)
		usage
		exit 2
		;;
	*)
		plot_data "$@"
		;;
esac

