# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Simple MAV simulator settings
habitat_ros_mav_sim:
  sim_freq: 60
  a_max: [1.0, 1.0, 0.5]
  w_max: [0.1, 0.1, 0.05]
  world_frame_id: "world"

