# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 100
  max_exploration_time: 900

# Supereight settings
supereight:
  map:
    size:                       256
    dim:                        51.2
    t_MW_factor:                [0.501, 0.501, 0.501]
    aabb_min_W:                 [-16.5, -15.5,  0.0]
    aabb_max_W:                 [ 16.5,  15.5, 26.0]
    sampling_min_W:             [-.inf, -.inf,  0.7]
    sampling_max_W:             [ .inf,  .inf, 25.0]

  sensor:
    near_plane:                 0.02
    far_plane:                  7.0

  exploration:
    delta_t:                    0.20

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

