# SPDX-FileCopyrightText: 2019-2020 Smart Robotics Lab, Imperial College London
# SPDX-FileCopyrightText: 2019 Anna Dai
# SPDX-FileCopyrightText: 2020 Sotiris Papatheodorou
# SPDX-License-Identifier: CC0-1.0

# Supereight ROS node settings
supereight_ros:
  visualization_max_z: 2.85
  max_exploration_time: 300

# Supereight settings
supereight:
  map:
    size:                       256
    dim:                        25.6
    t_MW_factor:                [0.501, 0.501, 0.501]
    aabb_min_W:                 [-5.0, -10.0, 0.0]
    aabb_max_W:                 [ 5.0,  10.0, 3.0]

  exploration:
    delta_t:                    0.50

# WARNING: Any voxel parameters added in this file will be ignored. Change the
# defaults if you need different values.

